default_page: /home # custom page or absolute url

pages:
  - title: Home
    path: /home
    # inject:
    #   css:
    #   html:
    #   js:
    search:
     enabled: true
     label: DuckDuckGo
     url: https://duckduckgo.com/search?q=%s
    #widgets: #live in html files, injected as iframe
    #  - builtin: host_cpu
    #  - inject: /some/file.html
    #    kv:
    #      some_key: some_value
    
    links:
      - title: link0
        # icon: # favicon if unset
        color: "#E26D5C"
        url: https://ads.google.com
      - title: link1
        url: https://google.com