default_page: /home # custom page or absolute url

pages:
  - title: Home
    path: /home
    # inject:
    #   css:
    #   html:
    #   js:
    search:
     enabled: true
     label: DuckDuckGo
     url: https://duckduckgo.com/?q=%s
    widgets: # injected as iframe
    #  - inject: http://url.com
    
    links:
      - title: link0
        # icon: # favicon if unset
        color: "#E26D5C"
        url: https://ads.google.com
      - title: link1
        url: https://google.com